buildpacks = [
  { id = "org.cloudfoundry.buildsystem",    uri = "https://repo.spring.io/libs-snapshot-local/org/cloudfoundry/buildsystem/org.cloudfoundry.buildsystem/1.0.0-BUILD-SNAPSHOT/org.cloudfoundry.buildsystem-1.0.0-BUILD-20180921.204046-1.tgz",    latest = true },
  { id = "org.cloudfoundry.debug",          uri = "https://repo.spring.io/libs-snapshot-local/org/cloudfoundry/debug/org.cloudfoundry.debug/1.0.0-BUILD-SNAPSHOT/org.cloudfoundry.debug-1.0.0-BUILD-20181114.222112-1.tgz",           latest = true },
  { id = "org.cloudfoundry.jmx",            uri = "https://repo.spring.io/libs-snapshot-local/org/cloudfoundry/jmx/org.cloudfoundry.jmx/1.0.0-BUILD-SNAPSHOT/org.cloudfoundry.jmx-1.0.0-BUILD-20181130.221013-1.tgz",             latest = true },
  { id = "org.cloudfoundry.jvmapplication", uri = "https://repo.spring.io/libs-snapshot-local/org/cloudfoundry/jvmapplication/org.cloudfoundry.jvmapplication/1.0.0-BUILD-SNAPSHOT/org.cloudfoundry.jvmapplication-1.0.0-BUILD-20180921.203339-1.tgz", latest = true },
  { id = "org.cloudfoundry.openjdk",        uri = "https://repo.spring.io/libs-snapshot-local/org/cloudfoundry/openjdk/org.cloudfoundry.openjdk/1.0.0-BUILD-SNAPSHOT/org.cloudfoundry.openjdk-1.0.0-BUILD-20180921.211503-1.tgz",         latest = true },
]

[[groups]]
labels = [ "java" ]
buildpacks = [
  { id = "org.cloudfoundry.openjdk",        version = "1.0.0-BUILD-SNAPSHOT" },
  { id = "org.cloudfoundry.buildsystem",    version = "1.0.0-BUILD-SNAPSHOT", optional = true },
  { id = "org.cloudfoundry.jvmapplication", version = "1.0.0-BUILD-SNAPSHOT" },
  { id = "org.cloudfoundry.debug",          version = "1.0.0-BUILD-SNAPSHOT", optional = true },
  { id = "org.cloudfoundry.jmx",            version = "1.0.0-BUILD-SNAPSHOT", optional = true },
]
